/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistematurnos;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author elian
 */
public class ProfesionalModificacion extends javax.swing.JFrame {

    private Connection con;
    private String Datos;
    private int IdBase;
    
    public ProfesionalModificacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IdProfesional = new javax.swing.JTextField();
        Especialidad = new javax.swing.JTextField();
        sad = new javax.swing.JLabel();
        Apellidos = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CorreoElectronico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Nro_Telefono = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        jLabel8.setText("Ejemplo: Juan.Perez@gmail.com");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modificacion de Profesional");

        jLabel7.setText("Id Profesional");

        IdProfesional.setText("IdProfesional");
        IdProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdProfesionalActionPerformed(evt);
            }
        });

        Especialidad.setText("DNI...");
        Especialidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EspecialidadFocusGained(evt);
            }
        });
        Especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialidadActionPerformed(evt);
            }
        });

        sad.setText("Ingrese la Especialidad");

        Apellidos.setText("Apellidos");
        Apellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ApellidosFocusGained(evt);
            }
        });

        Apellido.setText("Ingrese el Apellido");

        jLabel4.setText("Ingrese el Nombres");

        Nombres.setText("Apellido...");
        Nombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombresFocusGained(evt);
            }
        });

        jLabel5.setText("Ingrese el Correo Electronico");

        CorreoElectronico.setText("Correo Electronico");
        CorreoElectronico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CorreoElectronicoFocusGained(evt);
            }
        });
        CorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoElectronicoActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingrese el Correo Numero de Telefono");

        Nro_Telefono.setText("01155555555");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificar)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Apellido)
                    .addComponent(sad)
                    .addComponent(Nro_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(IdProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IdProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sad)
                .addGap(11, 11, 11)
                .addComponent(Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Apellido)
                .addGap(11, 11, 11)
                .addComponent(Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nro_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnModificar))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdProfesionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdProfesionalActionPerformed

    private void EspecialidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EspecialidadFocusGained
        Especialidad.setText("");
    }//GEN-LAST:event_EspecialidadFocusGained

    private void EspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspecialidadActionPerformed

    private void ApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ApellidosFocusGained
        Apellidos.setText("");
    }//GEN-LAST:event_ApellidosFocusGained

    private void NombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombresFocusGained
        Nombres.setText("");
    }//GEN-LAST:event_NombresFocusGained

    private void CorreoElectronicoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CorreoElectronicoFocusGained
        CorreoElectronico.setText("");
    }//GEN-LAST:event_CorreoElectronicoFocusGained

    private void CorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoElectronicoActionPerformed

    }//GEN-LAST:event_CorreoElectronicoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(!true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        //incicializo Clase Auxiliar que ingresando un string devuelve verdadero si todos los caracteres son numeros
        Auxiliares Comparador = new Auxiliares(Especialidad.getText());
        boolean esNumerico = Auxiliares.isNumeric(Especialidad.getText());

        //Comparo si DNI esta vasio o si tiene letras
        if (Especialidad.getText().equals("") || !esNumerico) {
            JOptionPane.showMessageDialog(Especialidad, "El campo DNI esta incompleto o posee letras");
            return;
        }

        //Evaluo si el Nummero de telefono posee Letras (Contemplo la posibilidad de que alguien no tenga momentaneamente numero de telefono
            if (CorreoElectronico.getText().equals("")) {
                CorreoElectronico.setText("0");
            }

            if (!esNumerico) {
                JOptionPane.showMessageDialog(Especialidad, "El campo Numero telefonico posee letras caracteres no numericos");
                return;
            }

            if (Apellidos.getText().equals("")) {
                JOptionPane.showMessageDialog(Especialidad, "El campo Nombre esta incompleto");
                return;
            }
            if (Nombres.getText().equals("")) {
                JOptionPane.showMessageDialog(Especialidad, "El campo Apellido esta incompleto");
                return;
            }

            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/gestionturnos", "root", "");
                Statement stmt = con.createStatement();
                //La siguiente sentencia SQL es la linea ideal pero por un error java.sql.SQLSyntaxErrorException: Unknown column 'Remaggi' in 'field list' en el que toma los valores ignresados como columnas, no puedo utilizarla
                //Existe un error en los campos Nombres y apellidos
                stmt.executeUpdate("UPDATE profesionales SET IdProfesional = " + IdProfesional.getText() + ", Nombres =" + this.Apellidos.getText()+", Apellidos = " + this.Nombres.getText()+ ", DNI=" + Especialidad.getText() + ", Mail=" + Especialidad.getText() + ", Nro_Telefono=" + CorreoElectronico.getText() + " WHERE IdProfesional=" + IdBase
                );

                //Horrible, poco practico, pero eficaz
                /*stmt.executeUpdate("UPDATE clientes SET Nombres="+Nombres.getText()+" WHERE IdCliente="+IdBase);
                stmt.executeUpdate("UPDATE clientes SET Apellidos = "+Apellidos.getText()+" WHERE IdCliente="+IdBase);
                stmt.executeUpdate("UPDATE clientes SET DNI = "+DNI.getText()+" WHERE IdCliente="+IdBase);
                stmt.executeUpdate("UPDATE clientes SET Mail = "+Mail.getText()+" WHERE IdCliente="+IdBase);
                stmt.executeUpdate("UPDATE clientes SET Nro_Telefono = "+Nro_Telefono.getText()+" WHERE IdCliente="+IdBase);
                stmt.executeUpdate("UPDATE clientes SET IdCliente = "+IdCliente.getText()+" WHERE IdCliente="+IdBase);
                */
                JOptionPane.showMessageDialog(this, "Cliente modificado con exito");
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(ClienteRegistro.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "No se puede modificar el cliente ahora");
            }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfesionalModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfesionalModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfesionalModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfesionalModificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfesionalModificacion().setVisible(true);
            }
        });
    }
    public void setDatos(String Datos) {
        this.Datos = Datos;
        Datos = Datos.replaceAll("[\\[\\]\\ ]", "");
        String[] vect = Datos.split(",");
        IdBase = Integer.parseInt(vect[0]);
        IdProfesional.setText(vect[0]);
        Apellidos.setText(vect[1]);
        Nombres.setText(vect[2]);
        Especialidad.setText(vect[3]);
        Nro_Telefono.setText(vect[4]);
        CorreoElectronico.setText(vect[5]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JTextField Apellidos;
    private javax.swing.JTextField CorreoElectronico;
    private javax.swing.JTextField Especialidad;
    private javax.swing.JTextField IdProfesional;
    private javax.swing.JTextField Nombres;
    private javax.swing.JTextField Nro_Telefono;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel sad;
    // End of variables declaration//GEN-END:variables
}
